name: Build, Push, and Run colcon Build

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      image_name: ${{ steps.extract.outputs.image_name }}
      image_tag: ${{ steps.extract.outputs.image_tag }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Extract Variables
        id: extract
        run: |
          REPO_NAME="${GITHUB_REPOSITORY##*/}"
          BRANCH_NAME="${GITHUB_REF#refs/heads/}"
          BRANCH_NAME="${BRANCH_NAME//\//-}"
          SHORT_COMMIT_HASH=$(git rev-parse --short HEAD)
          IMAGE_NAME="ghcr.io/${GITHUB_REPOSITORY_OWNER}/${REPO_NAME}"
          IMAGE_TAG="${BRANCH_NAME}-${SHORT_COMMIT_HASH}"
          echo "::set-output name=image_name::$IMAGE_NAME"
          echo "::set-output name=image_tag::$IMAGE_TAG"

      # Set up Buildx with the docker-container driver
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver: docker-container

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ steps.extract.outputs.image_name }}:${{ steps.extract.outputs.image_tag }}
          cache-from: type=registry,ref=${{ steps.extract.outputs.image_name }}:cache
          cache-to: type=registry,ref=${{ steps.extract.outputs.image_name }}:cache,mode=max

  colcon_build:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull Docker Image
        run: |
          docker pull ${{ needs.build.outputs.image_name }}:${{ needs.build.outputs.image_tag }}

      - name: Run colcon build in Docker Container
        run: |
          docker run --rm -w /home/ubuntu/ros_ws \
            ${{ needs.build.outputs.image_name }}:${{ needs.build.outputs.image_tag }} \
            bash -c "source /opt/ros/humble/setup.bash && colcon build"
