name: Build, Push, and Update README with GHCR Tag

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      image_name: ${{ steps.extract.outputs.image_name }}
      image_tag: ${{ steps.extract.outputs.image_tag }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Extract Variables
        id: extract
        run: |
          REPO_NAME="${GITHUB_REPOSITORY##*/}"
          BRANCH_NAME="${GITHUB_REF#refs/heads/}"
          BRANCH_NAME="${BRANCH_NAME//\//-}"
          SHORT_COMMIT_HASH=$(git rev-parse --short HEAD)
          IMAGE_NAME="ghcr.io/${GITHUB_REPOSITORY_OWNER}/${REPO_NAME}"
          IMAGE_TAG="${BRANCH_NAME}-${SHORT_COMMIT_HASH}"
          echo "IMAGE_NAME=${IMAGE_NAME}" >> $GITHUB_ENV
          echo "IMAGE_TAG=${IMAGE_TAG}" >> $GITHUB_ENV
          echo "::set-output name=image_name::$IMAGE_NAME"
          echo "::set-output name=image_tag::$IMAGE_TAG"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver: docker-container

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          cache-from: type=registry,ref=${{ env.IMAGE_NAME }}:cache
          cache-to: type=registry,ref=${{ env.IMAGE_NAME }}:cache,mode=max

  colcon_build:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull Docker Image
        run: |
          docker pull ${{ needs.build.outputs.image_name }}:${{ needs.build.outputs.image_tag }}

      - name: Run colcon build in Docker Container
        run: |
          docker run --rm -w /home/ubuntu/ros_ws \
            ${{ needs.build.outputs.image_name }}:${{ needs.build.outputs.image_tag }} \
            bash -c "source /opt/ros/humble/setup.bash && colcon build"

  update_readme:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'  # Only update README on main branch
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update README.md with Latest GHCR Tag
        run: |
          TAG="${{ needs.build.outputs.image_tag }}"
          IMAGE_URL="https://github.com/${{ github.repository }}/pkgs/container/basic_offboard_px4?tag=$TAG"

          # Update the badge in README.md
          sed -i "s|!\[GHCR Latest Image\](.*)|![GHCR Latest Image](https://img.shields.io/badge/GHCR-$TAG-blue?logo=docker)|g" README.md

          # Commit and push changes
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Update GHCR badge with latest tag: $TAG" || echo "No changes to commit"
          git push origin main
